### ISSUE TITLE
Rally is being ignored a bit too much

### ISSUE THREAD

**Issue by asimonet** [BeyondTheClouds/kolla-g5k#34]
The line `rally` in `.gitignore`may be a bit too coarse grained (at least for my use-case). Because of it, modifications made to some files are ignored when (I think) they should not, in particular to:
- `rally/launch_scenario.sh` (which is code, so it makes sense to commit changes made there)
- `ansible/roles/bench/tasks/rally.yml`

I think we need a more fine-grained rule for rally but I am not sure exactly what the rule was meant to ignore, so I am leaving it to the guys who know.

**Comment by msimonin** [comment]
If you make some modification in files you want to versionned under the rally directory, you can use `git add -f`
Ignoring the whole directory was initially made  to do what you want inside without caring too much about polluting the git history (e.g maintain your own list of scenarios).

By the way, having `rally/` would be better to avoid any side effects on the ansible rally task.
We should at least change that.

**Comment by msimonin** [comment]
fixed
